package org.lkop.MINIC2C;

public enum CodeNodeType {
        CB_NA,
        CB_FILE,
        CB_FUNCTIONDEFINITION,
        CB_EXPRESSIONSTATEMENT,
        CB_RETURNSTATEMENT,
        CB_IFSTATEMENT,
        CB_WHILESTATEMENT,
        CB_DOWHILESTATEMENT,
        CB_FORLOOPSTATEMENT,
        CB_CONDITION,
        CB_COMPOUNDSTATEMENT,
        CB_CODEREPOSITORY
}
